rules:
  unpinned-uses:
    config:
      allow:
        - actions/checkout@v5
        - actions/setup-go@v5
        - actions/setup-node@v4
        - actions/download-artifact@v4
        - actions/upload-artifact@v4
        