rules:
  unpinned-uses:
    config:
      policies:
        # Trusted GitHub-maintained action
        actions/checkout: ref-pin
        actions/setup-go: ref-pin
        actions/setup-node: ref-pin
        actions/download-artifact: ref-pin
        actions/upload-artifact: ref-pin
        actions/stale: ref-pin
        # Trust vecahin maintained action
        vechain/hayabusa-e2e/.github/workflows/run-tests.yaml: ref-pin
