# See: https://github.com/apache/skywalking-eyes
header:
  license:
    spdx-id: GPL-3.0-or-later
    # This is the pattern used when running:
    #   docker run -it --rm -v $(pwd):/github/workspace apache/skywalking-eyes header check
    pattern: |
      Copyright(?: \(c\))? \b(19\d{2}|20\d{2})\b The (VeChainThor developers|go-ethereum Authors)
    # This is content written to files when running:
    #   docker run -it --rm -v $(pwd):/github/workspace apache/skywalking-eyes header fix
    content: |
      Copyright (c) 2025 The VeChainThor developers
      
      Distributed under the GNU Lesser General Public License v3.0 software license, see the accompanying
      file LICENSE or <https://www.gnu.org/licenses/lgpl-3.0.html>
  paths:
    - '**/*.go'
  paths-ignore:
    - 'builtin/gen/bindata.go'
    - 'tracers/**/gen_*.go'
