# Build thor in a stock Go builder container
FROM golang:1.10-alpine as builder
RUN apk add --no-cache make gcc musl-dev linux-headers git
RUN git clone https://github.com/vechain/thor.git thor-test
WORKDIR  /go/thor-test
RUN git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
RUN make dep && make thor

# Pull thor into a second stage deploy alpine container
FROM alpine:latest
RUN apk add --no-cache ca-certificates g++ python3-dev libffi-dev openssl-dev && \
    apk add --no-cache --update python3 && \
    pip3 install --upgrade pip setuptools
RUN pip3 install web3-gear
COPY --from=builder /go/thor-test/bin/thor /usr/local/bin/

EXPOSE 8669 11223 11223/udp
# ENTRYPOINT ["thor"]