package vm

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/params"
	"github.com/vechain/thor/thor"
	"github.com/vechain/thor/vm/evm"
	"github.com/vechain/thor/vm/statedb"
)

// Config is ref to evm.Config.
type Config evm.Config

// Output contains the execution return value.
type Output struct {
	Value             []byte
	Logs              []*Log
	AffectedAddresses []thor.Address // addresses which balance changed
	LeftOverGas       uint64
	RefundGas         *big.Int
	Preimages         map[thor.Hash][]byte
	VMErr             error         // VMErr identify the execution result of the contract function, not evm function's err.
	ContractAddress   *thor.Address // if create a new contract, or is nil.
}

// Log represents a contract log event. These events are generated by the LOG opcode and
// stored/indexed by the node.
type Log statedb.Log

// State to decouple with state.State
type State statedb.State

// VM is a facade for ethEvm.
type VM struct {
	evm     *evm.EVM
	statedb *statedb.StateDB
}

var chainConfig = &params.ChainConfig{
	ChainId:        big.NewInt(0),
	HomesteadBlock: big.NewInt(0),
	DAOForkBlock:   big.NewInt(0),
	DAOForkSupport: false,
	EIP150Block:    big.NewInt(0),
	EIP150Hash:     common.Hash{},
	EIP155Block:    big.NewInt(0),
	EIP158Block:    big.NewInt(0),
	ByzantiumBlock: big.NewInt(0),
	Ethash:         nil,
	Clique:         nil,
}

// Context for VM runtime.
type Context struct {
	Origin      thor.Address
	Beneficiary thor.Address
	BlockNumber *big.Int
	Time        *big.Int
	GasLimit    *big.Int
	GasPrice    *big.Int
	TxHash      thor.Hash
	ClauseIndex uint64
	GetHash     func(uint32) thor.Hash
}

// The only purpose of this func separate definition is to be compatible with evm.context.
func canTransfer(db evm.StateDB, addr common.Address, amount *big.Int) bool {
	return db.GetBalance(addr).Cmp(amount) >= 0
}

// The only purpose of this func separate definition is to be compatible with evm.Context.
func transfer(db evm.StateDB, sender, recipient common.Address, amount *big.Int) {
	db.SubBalance(sender, amount)
	db.AddBalance(recipient, amount)
}

// New retutrns a new EVM . The returned EVM is not thread safe and should
// only ever be used *once*.
func New(ctx Context, state State, vmConfig Config) *VM {
	tGetHash := func(n uint64) common.Hash {
		return common.Hash(ctx.GetHash(uint32(n)))
	}

	statedb := statedb.New(state)
	evmCtx := evm.Context{
		CanTransfer: canTransfer,
		Transfer:    transfer,
		GetHash:     tGetHash,
		Difficulty:  new(big.Int),

		Origin:      common.Address(ctx.Origin),
		Coinbase:    common.Address(ctx.Beneficiary),
		BlockNumber: ctx.BlockNumber,
		Time:        ctx.Time,
		GasLimit:    ctx.GasLimit,
		GasPrice:    ctx.GasPrice,
		TxHash:      common.Hash(ctx.TxHash),
	}
	evm := evm.NewEVM(evmCtx, statedb, chainConfig, evm.Config(vmConfig))

	return &VM{evm, statedb}
}

// Cancel cancels any running EVM operation.
// This may be called concurrently and it's safe to be called multiple times.
func (vm *VM) Cancel() {
	vm.evm.Cancel()
}

// Call executes the contract associated with the addr with the given input as parameters.
// It also handles any necessary value transfer required and takes the necessary steps to
// create accounts and reverses the state in case of an execution error or failed value transfer.
func (vm *VM) Call(caller thor.Address, addr thor.Address, input []byte, gas uint64, value *big.Int) *Output {
	ret, leftOverGas, vmErr := vm.evm.Call(&vmContractRef{caller}, common.Address(addr), input, gas, value)
	logs, affectedAddrs, preimages := vm.extractStateDBOutputs()
	return &Output{ret, logs, affectedAddrs, leftOverGas, vm.statedb.GetRefund(), preimages, vmErr, nil}
}

// CallCode executes the contract associated with the addr with the given input as parameters.
// It also handles any necessary value transfer required and takes the necessary steps to create
// accounts and reverses the state in case of an execution error or failed value transfer.
//
// CallCode differs from Call in the sense that it executes the given address'
// code with the caller as context.
func (vm *VM) CallCode(caller thor.Address, addr thor.Address, input []byte, gas uint64, value *big.Int) *Output {
	ret, leftOverGas, vmErr := vm.evm.CallCode(&vmContractRef{caller}, common.Address(addr), input, gas, value)
	logs, affectedAddrs, preimages := vm.extractStateDBOutputs()
	return &Output{ret, logs, affectedAddrs, leftOverGas, vm.statedb.GetRefund(), preimages, vmErr, nil}
}

// DelegateCall executes the contract associated with the addr with the given input as parameters.
// It reverses the state in case of an execution error.
//
// DelegateCall differs from CallCode in the sense that it executes the given address' code with
// the caller as context and the caller is set to the caller of the caller.
func (vm *VM) DelegateCall(caller thor.Address, addr thor.Address, input []byte, gas uint64) *Output {
	ret, leftOverGas, vmErr := vm.evm.DelegateCall(&vmContractRef{caller}, common.Address(addr), input, gas)
	logs, affectedAddrs, preimages := vm.extractStateDBOutputs()
	return &Output{ret, logs, affectedAddrs, leftOverGas, vm.statedb.GetRefund(), preimages, vmErr, nil}
}

// StaticCall executes the contract associated with the addr with the given input as parameters
// while disallowing any modifications to the state during the call.
//
// Opcodes that attempt to perform such modifications will result in exceptions instead of performing
// the modifications.
func (vm *VM) StaticCall(caller thor.Address, addr thor.Address, input []byte, gas uint64) *Output {
	ret, leftOverGas, vmErr := vm.evm.StaticCall(&vmContractRef{caller}, common.Address(addr), input, gas)
	logs, affectedAddrs, preimages := vm.extractStateDBOutputs()
	return &Output{ret, logs, affectedAddrs, leftOverGas, vm.statedb.GetRefund(), preimages, vmErr, nil}
}

// Create creates a new contract using code as deployment code.
func (vm *VM) Create(caller thor.Address, code []byte, gas uint64, value *big.Int) *Output {
	ret, contractAddr, leftOverGas, vmErr := vm.evm.Create(&vmContractRef{caller}, code, gas, value)
	contractAddress := thor.Address(contractAddr)
	logs, affectedAddrs, preimages := vm.extractStateDBOutputs()
	return &Output{ret, logs, affectedAddrs, leftOverGas, vm.statedb.GetRefund(), preimages, vmErr, &contractAddress}
}

// ChainConfig returns the evmironment's chain configuration
func (vm *VM) ChainConfig() *params.ChainConfig {
	return vm.evm.ChainConfig()
}

func (vm *VM) extractStateDBOutputs() (logs []*Log, affectedAdds []thor.Address, preimages map[thor.Hash][]byte) {
	vm.statedb.GetOutputs(
		func(log *statedb.Log) bool {
			logs = append(logs, (*Log)(log))
			return true
		},
		func(newAddr thor.Address) bool {
			affectedAdds = append(affectedAdds, newAddr)
			return true
		},
		func(key thor.Hash, value []byte) bool {
			// create on-demand
			if preimages == nil {
				preimages = make(map[thor.Hash][]byte)
			}
			preimages[key] = value
			return true
		},
	)
	return
}
