/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface InferenceMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CHALLENGER_BOND"
      | "CHALLENGE_WINDOW"
      | "FRAUD_THRESHOLD"
      | "MIN_CHECKER_STAKE"
      | "MIN_INFERENCE_STAKE"
      | "checkerNodes"
      | "finalizeResponse"
      | "getRequest"
      | "getResponse"
      | "inferenceNodes"
      | "models"
      | "registerCheckerNode"
      | "registerInferenceNode"
      | "registerModel"
      | "requests"
      | "responses"
      | "submitFraudProof"
      | "submitRequest"
      | "submitResponse"
      | "submitVerdict"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CheckerNodeRegistered"
      | "FraudProofAccepted"
      | "InferenceNodeRegistered"
      | "InferenceRequested"
      | "InferenceResponded"
      | "ModelRegistered"
      | "NodeSlashed"
      | "ResponseFinalized"
      | "VerdictSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CHALLENGER_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CHALLENGE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FRAUD_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_CHECKER_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_INFERENCE_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkerNodes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeResponse",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResponse",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "inferenceNodes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "models", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerCheckerNode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerInferenceNode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerModel",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "requests", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "responses",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitFraudProof",
    values: [
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike[],
      BytesLike[],
      BytesLike[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRequest",
    values: [string, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResponse",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitVerdict",
    values: [BytesLike, boolean, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "CHALLENGER_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CHALLENGE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FRAUD_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_CHECKER_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_INFERENCE_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkerNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inferenceNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "models", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCheckerNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerInferenceNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerModel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "responses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitFraudProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitVerdict",
    data: BytesLike
  ): Result;
}

export namespace CheckerNodeRegisteredEvent {
  export type InputTuple = [node: AddressLike, stake: BigNumberish];
  export type OutputTuple = [node: string, stake: bigint];
  export interface OutputObject {
    node: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FraudProofAcceptedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    challenger: AddressLike,
    disputedIndex: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    challenger: string,
    disputedIndex: bigint
  ];
  export interface OutputObject {
    requestId: string;
    challenger: string;
    disputedIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InferenceNodeRegisteredEvent {
  export type InputTuple = [node: AddressLike, stake: BigNumberish];
  export type OutputTuple = [node: string, stake: bigint];
  export interface OutputObject {
    node: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InferenceRequestedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    requester: AddressLike,
    model: string,
    inputHash: BytesLike,
    userPubkey: BytesLike,
    maxNewTokens: BigNumberish,
    payment: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    requester: string,
    model: string,
    inputHash: string,
    userPubkey: string,
    maxNewTokens: bigint,
    payment: bigint
  ];
  export interface OutputObject {
    requestId: string;
    requester: string;
    model: string;
    inputHash: string;
    userPubkey: string;
    maxNewTokens: bigint;
    payment: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InferenceRespondedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    prover: AddressLike,
    outputHash: BytesLike,
    modelCommitment: BytesLike,
    xRoot: BytesLike,
    zRoot: BytesLike,
    xEncoded: BytesLike,
    zEncoded: BytesLike
  ];
  export type OutputTuple = [
    requestId: string,
    prover: string,
    outputHash: string,
    modelCommitment: string,
    xRoot: string,
    zRoot: string,
    xEncoded: string,
    zEncoded: string
  ];
  export interface OutputObject {
    requestId: string;
    prover: string;
    outputHash: string;
    modelCommitment: string;
    xRoot: string;
    zRoot: string;
    xEncoded: string;
    zEncoded: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModelRegisteredEvent {
  export type InputTuple = [model: string, wRoot: BytesLike];
  export type OutputTuple = [model: string, wRoot: string];
  export interface OutputObject {
    model: string;
    wRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeSlashedEvent {
  export type InputTuple = [
    node: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [node: string, amount: bigint, reason: string];
  export interface OutputObject {
    node: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResponseFinalizedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    prover: AddressLike,
    payment: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    prover: string,
    payment: bigint
  ];
  export interface OutputObject {
    requestId: string;
    prover: string;
    payment: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerdictSubmittedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    checker: AddressLike,
    valid: boolean,
    reason: string
  ];
  export type OutputTuple = [
    requestId: string,
    checker: string,
    valid: boolean,
    reason: string
  ];
  export interface OutputObject {
    requestId: string;
    checker: string;
    valid: boolean;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InferenceMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): InferenceMarketplace;
  waitForDeployment(): Promise<this>;

  interface: InferenceMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CHALLENGER_BOND: TypedContractMethod<[], [bigint], "view">;

  CHALLENGE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  FRAUD_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MIN_CHECKER_STAKE: TypedContractMethod<[], [bigint], "view">;

  MIN_INFERENCE_STAKE: TypedContractMethod<[], [bigint], "view">;

  checkerNodes: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { stake: bigint; active: boolean }],
    "view"
  >;

  finalizeResponse: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  getRequest: TypedContractMethod<
    [requestId: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, boolean, boolean] & {
        requester: string;
        model: string;
        inputHash: string;
        maxNewTokens: bigint;
        payment: bigint;
        blockNum: bigint;
        responded: boolean;
        finalized: boolean;
      }
    ],
    "view"
  >;

  getResponse: TypedContractMethod<
    [requestId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        prover: string;
        outputHash: string;
        modelCommitment: string;
        xRoot: string;
        zRoot: string;
        blockNum: bigint;
        slashed: boolean;
        fraudVotes: bigint;
        validVotes: bigint;
      }
    ],
    "view"
  >;

  inferenceNodes: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { stake: bigint; active: boolean }],
    "view"
  >;

  models: TypedContractMethod<
    [arg0: string],
    [[string, boolean] & { wRoot: string; registered: boolean }],
    "view"
  >;

  registerCheckerNode: TypedContractMethod<[], [void], "payable">;

  registerInferenceNode: TypedContractMethod<[], [void], "payable">;

  registerModel: TypedContractMethod<
    [model: string, wRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  requests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, boolean, boolean] & {
        requester: string;
        model: string;
        inputHash: string;
        maxNewTokens: bigint;
        payment: bigint;
        blockNumber: bigint;
        responded: boolean;
        finalized: boolean;
      }
    ],
    "view"
  >;

  responses: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        prover: string;
        outputHash: string;
        modelCommitment: string;
        xRoot: string;
        zRoot: string;
        blockNumber: bigint;
        slashed: boolean;
        fraudVoteCount: bigint;
        validVoteCount: bigint;
      }
    ],
    "view"
  >;

  submitFraudProof: TypedContractMethod<
    [
      requestId: BytesLike,
      disputedIndex: BigNumberish,
      wRowBytes: BytesLike,
      wMerklePath: BytesLike[],
      xMerklePath: BytesLike[],
      zMerklePath: BytesLike[],
      x_i: BigNumberish,
      z_i: BigNumberish
    ],
    [void],
    "payable"
  >;

  submitRequest: TypedContractMethod<
    [
      model: string,
      inputHash: BytesLike,
      userPubkey: BytesLike,
      maxNewTokens: BigNumberish
    ],
    [string],
    "payable"
  >;

  submitResponse: TypedContractMethod<
    [
      requestId: BytesLike,
      outputHash: BytesLike,
      modelCommitment: BytesLike,
      xRoot: BytesLike,
      zRoot: BytesLike,
      xEncoded: BytesLike,
      zEncoded: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitVerdict: TypedContractMethod<
    [requestId: BytesLike, valid: boolean, reason: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CHALLENGER_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CHALLENGE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FRAUD_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_CHECKER_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_INFERENCE_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkerNodes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { stake: bigint; active: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizeResponse"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, boolean, boolean] & {
        requester: string;
        model: string;
        inputHash: string;
        maxNewTokens: bigint;
        payment: bigint;
        blockNum: bigint;
        responded: boolean;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResponse"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        prover: string;
        outputHash: string;
        modelCommitment: string;
        xRoot: string;
        zRoot: string;
        blockNum: bigint;
        slashed: boolean;
        fraudVotes: bigint;
        validVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "inferenceNodes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, boolean] & { stake: bigint; active: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "models"
  ): TypedContractMethod<
    [arg0: string],
    [[string, boolean] & { wRoot: string; registered: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerCheckerNode"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "registerInferenceNode"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "registerModel"
  ): TypedContractMethod<
    [model: string, wRoot: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, boolean, boolean] & {
        requester: string;
        model: string;
        inputHash: string;
        maxNewTokens: bigint;
        payment: bigint;
        blockNumber: bigint;
        responded: boolean;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "responses"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        prover: string;
        outputHash: string;
        modelCommitment: string;
        xRoot: string;
        zRoot: string;
        blockNumber: bigint;
        slashed: boolean;
        fraudVoteCount: bigint;
        validVoteCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitFraudProof"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      disputedIndex: BigNumberish,
      wRowBytes: BytesLike,
      wMerklePath: BytesLike[],
      xMerklePath: BytesLike[],
      zMerklePath: BytesLike[],
      x_i: BigNumberish,
      z_i: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "submitRequest"
  ): TypedContractMethod<
    [
      model: string,
      inputHash: BytesLike,
      userPubkey: BytesLike,
      maxNewTokens: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "submitResponse"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      outputHash: BytesLike,
      modelCommitment: BytesLike,
      xRoot: BytesLike,
      zRoot: BytesLike,
      xEncoded: BytesLike,
      zEncoded: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitVerdict"
  ): TypedContractMethod<
    [requestId: BytesLike, valid: boolean, reason: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CheckerNodeRegistered"
  ): TypedContractEvent<
    CheckerNodeRegisteredEvent.InputTuple,
    CheckerNodeRegisteredEvent.OutputTuple,
    CheckerNodeRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "FraudProofAccepted"
  ): TypedContractEvent<
    FraudProofAcceptedEvent.InputTuple,
    FraudProofAcceptedEvent.OutputTuple,
    FraudProofAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "InferenceNodeRegistered"
  ): TypedContractEvent<
    InferenceNodeRegisteredEvent.InputTuple,
    InferenceNodeRegisteredEvent.OutputTuple,
    InferenceNodeRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "InferenceRequested"
  ): TypedContractEvent<
    InferenceRequestedEvent.InputTuple,
    InferenceRequestedEvent.OutputTuple,
    InferenceRequestedEvent.OutputObject
  >;
  getEvent(
    key: "InferenceResponded"
  ): TypedContractEvent<
    InferenceRespondedEvent.InputTuple,
    InferenceRespondedEvent.OutputTuple,
    InferenceRespondedEvent.OutputObject
  >;
  getEvent(
    key: "ModelRegistered"
  ): TypedContractEvent<
    ModelRegisteredEvent.InputTuple,
    ModelRegisteredEvent.OutputTuple,
    ModelRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "NodeSlashed"
  ): TypedContractEvent<
    NodeSlashedEvent.InputTuple,
    NodeSlashedEvent.OutputTuple,
    NodeSlashedEvent.OutputObject
  >;
  getEvent(
    key: "ResponseFinalized"
  ): TypedContractEvent<
    ResponseFinalizedEvent.InputTuple,
    ResponseFinalizedEvent.OutputTuple,
    ResponseFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "VerdictSubmitted"
  ): TypedContractEvent<
    VerdictSubmittedEvent.InputTuple,
    VerdictSubmittedEvent.OutputTuple,
    VerdictSubmittedEvent.OutputObject
  >;

  filters: {
    "CheckerNodeRegistered(address,uint256)": TypedContractEvent<
      CheckerNodeRegisteredEvent.InputTuple,
      CheckerNodeRegisteredEvent.OutputTuple,
      CheckerNodeRegisteredEvent.OutputObject
    >;
    CheckerNodeRegistered: TypedContractEvent<
      CheckerNodeRegisteredEvent.InputTuple,
      CheckerNodeRegisteredEvent.OutputTuple,
      CheckerNodeRegisteredEvent.OutputObject
    >;

    "FraudProofAccepted(bytes32,address,uint256)": TypedContractEvent<
      FraudProofAcceptedEvent.InputTuple,
      FraudProofAcceptedEvent.OutputTuple,
      FraudProofAcceptedEvent.OutputObject
    >;
    FraudProofAccepted: TypedContractEvent<
      FraudProofAcceptedEvent.InputTuple,
      FraudProofAcceptedEvent.OutputTuple,
      FraudProofAcceptedEvent.OutputObject
    >;

    "InferenceNodeRegistered(address,uint256)": TypedContractEvent<
      InferenceNodeRegisteredEvent.InputTuple,
      InferenceNodeRegisteredEvent.OutputTuple,
      InferenceNodeRegisteredEvent.OutputObject
    >;
    InferenceNodeRegistered: TypedContractEvent<
      InferenceNodeRegisteredEvent.InputTuple,
      InferenceNodeRegisteredEvent.OutputTuple,
      InferenceNodeRegisteredEvent.OutputObject
    >;

    "InferenceRequested(bytes32,address,string,bytes32,bytes32,uint32,uint256)": TypedContractEvent<
      InferenceRequestedEvent.InputTuple,
      InferenceRequestedEvent.OutputTuple,
      InferenceRequestedEvent.OutputObject
    >;
    InferenceRequested: TypedContractEvent<
      InferenceRequestedEvent.InputTuple,
      InferenceRequestedEvent.OutputTuple,
      InferenceRequestedEvent.OutputObject
    >;

    "InferenceResponded(bytes32,address,bytes32,bytes32,bytes32,bytes32,bytes,bytes)": TypedContractEvent<
      InferenceRespondedEvent.InputTuple,
      InferenceRespondedEvent.OutputTuple,
      InferenceRespondedEvent.OutputObject
    >;
    InferenceResponded: TypedContractEvent<
      InferenceRespondedEvent.InputTuple,
      InferenceRespondedEvent.OutputTuple,
      InferenceRespondedEvent.OutputObject
    >;

    "ModelRegistered(string,bytes32)": TypedContractEvent<
      ModelRegisteredEvent.InputTuple,
      ModelRegisteredEvent.OutputTuple,
      ModelRegisteredEvent.OutputObject
    >;
    ModelRegistered: TypedContractEvent<
      ModelRegisteredEvent.InputTuple,
      ModelRegisteredEvent.OutputTuple,
      ModelRegisteredEvent.OutputObject
    >;

    "NodeSlashed(address,uint256,string)": TypedContractEvent<
      NodeSlashedEvent.InputTuple,
      NodeSlashedEvent.OutputTuple,
      NodeSlashedEvent.OutputObject
    >;
    NodeSlashed: TypedContractEvent<
      NodeSlashedEvent.InputTuple,
      NodeSlashedEvent.OutputTuple,
      NodeSlashedEvent.OutputObject
    >;

    "ResponseFinalized(bytes32,address,uint256)": TypedContractEvent<
      ResponseFinalizedEvent.InputTuple,
      ResponseFinalizedEvent.OutputTuple,
      ResponseFinalizedEvent.OutputObject
    >;
    ResponseFinalized: TypedContractEvent<
      ResponseFinalizedEvent.InputTuple,
      ResponseFinalizedEvent.OutputTuple,
      ResponseFinalizedEvent.OutputObject
    >;

    "VerdictSubmitted(bytes32,address,bool,string)": TypedContractEvent<
      VerdictSubmittedEvent.InputTuple,
      VerdictSubmittedEvent.OutputTuple,
      VerdictSubmittedEvent.OutputObject
    >;
    VerdictSubmitted: TypedContractEvent<
      VerdictSubmittedEvent.InputTuple,
      VerdictSubmittedEvent.OutputTuple,
      VerdictSubmittedEvent.OutputObject
    >;
  };
}
