name: Go module check

on:
  # Should only be used by other workflows
  workflow_call:

permissions:
  contents: read

jobs:
  go-mod-check:
    name: ensure go mod is tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false

      - name: go mod tidy
        run: |
          go mod tidy

      - name: check go module
        run: |
          if ! git diff --exit-code --quiet; then
            echo "Go module is not tidy, please run 'go mod tidy' and commit the changes"
            exit 1
          fi
