name: Notify Slack

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      payload:
        type: string
        required: true
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
  workflow_dispatch:
    inputs:
      payload:
        type: string
        required: true

jobs:
  notify:
    name: Notify Slack
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: ${{ inputs.payload }}
