name: Unit Tests

on:
  push:
    branches:
      - "*"
jobs:
  unit_tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache: 'true'

      - name: Make all
        run: go test ./txpool -run ^TestTxPool_Local_IncreasingPriority$